//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDashDouble
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DealDoubleDBContext : DbContext
    {
        public DealDoubleDBContext()
            : base("name=DealDoubleDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Auction> tbl_Auction { get; set; }
        public virtual DbSet<tbl_AuctionPicture> tbl_AuctionPicture { get; set; }
        public virtual DbSet<tbl_Picture> tbl_Picture { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
    }
}
