//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealDashDouble
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Comment
    {
        public int commentID { get; set; }

        [Required(ErrorMessage ="*")]
        public string Text { get; set; }
        public string UserID { get; set; }
        public System.DateTime TimpStamp { get; set; }

        [Required(ErrorMessage = "*")]
        public int EntityID { get; set; }
        [Required(ErrorMessage = "*")]
        public int RecordID { get; set; }
        public int Rating { get; set; }
    }
}
